[#ftl]
[#-- @implicitly included --]
[[#-- @ftlvariable name="shiro" type="com.jagregory.shiro.freemarker.ShiroTags" --]]
[#--系统管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_SYSTEM" type="java.lang.String" --]
[#--测试404--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_CESHI404" type="java.lang.String" --]
[#--测试500--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_CESHI500" type="java.lang.String" --]
[#--操作日志--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_OPERATE" type="java.lang.String" --]
[#--图标管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ICON" type="java.lang.String" --]
[#--用户管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_USER" type="java.lang.String" --]
[#--菜单管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_MENU" type="java.lang.String" --]
[#--角色管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ROLE" type="java.lang.String" --]
[#--组织机构管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_ORG" type="java.lang.String" --]
[#--文件管理--]
[#-- @ftlvariable name="PrivCode.MENU_CODE_FILE" type="java.lang.String" --]
[#--删除用户--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_USER_DELETE" type="java.lang.String" --]
[#--保存用户--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_USER_SAVE" type="java.lang.String" --]
[#--保存角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_SAVE" type="java.lang.String" --]
[#--删除角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_DELETE" type="java.lang.String" --]
[#--分配角色--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ROLE_ALLOT" type="java.lang.String" --]
[#--保存菜单--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MENU_SAVE" type="java.lang.String" --]
[#--删除菜单--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_MENU_DELETE" type="java.lang.String" --]
[#--保存组织机构--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ORG_SAVE" type="java.lang.String" --]
[#--删除组织机构--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_ORG_DELETE" type="java.lang.String" --]
[#--上传文件--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_FILE_UPLOAD" type="java.lang.String" --]
[#--删除文件--]
[#-- @ftlvariable name="PrivCode.BTN_CODE_FILE_DELETE" type="java.lang.String" --]
