server:
  port: 8088
  servlet:
    context-path: /qmplatform

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/qmplatform_single
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .ftl
  freemarker:
    request-context-attribute: requestContext

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml

# 分页插件
pagehelper:
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.qcz.qmplatform.module.**.mapper: debug

# 自定义属性
custom:
  upload-file-path: file:D:\workspace\file
